//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/PlayerInputSystem/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""BirdPlayer"",
            ""id"": ""75f3e150-9f56-4d35-9d33-767807dd9be4"",
            ""actions"": [
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""b82d2c70-affd-4e77-807d-dd09e5c25cf9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""84cd9289-e7a1-43cd-b659-bb6b3b169a06"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard&Mouse"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""135828d8-8aca-485e-9c38-b75591344333"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard&Mouse"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""keyboard&Mouse"",
            ""bindingGroup"": ""keyboard&Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // BirdPlayer
        m_BirdPlayer = asset.FindActionMap("BirdPlayer", throwIfNotFound: true);
        m_BirdPlayer_Jump = m_BirdPlayer.FindAction("Jump", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // BirdPlayer
    private readonly InputActionMap m_BirdPlayer;
    private IBirdPlayerActions m_BirdPlayerActionsCallbackInterface;
    private readonly InputAction m_BirdPlayer_Jump;
    public struct BirdPlayerActions
    {
        private @PlayerInput m_Wrapper;
        public BirdPlayerActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Jump => m_Wrapper.m_BirdPlayer_Jump;
        public InputActionMap Get() { return m_Wrapper.m_BirdPlayer; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BirdPlayerActions set) { return set.Get(); }
        public void SetCallbacks(IBirdPlayerActions instance)
        {
            if (m_Wrapper.m_BirdPlayerActionsCallbackInterface != null)
            {
                @Jump.started -= m_Wrapper.m_BirdPlayerActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_BirdPlayerActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_BirdPlayerActionsCallbackInterface.OnJump;
            }
            m_Wrapper.m_BirdPlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
            }
        }
    }
    public BirdPlayerActions @BirdPlayer => new BirdPlayerActions(this);
    private int m_keyboardMouseSchemeIndex = -1;
    public InputControlScheme keyboardMouseScheme
    {
        get
        {
            if (m_keyboardMouseSchemeIndex == -1) m_keyboardMouseSchemeIndex = asset.FindControlSchemeIndex("keyboard&Mouse");
            return asset.controlSchemes[m_keyboardMouseSchemeIndex];
        }
    }
    public interface IBirdPlayerActions
    {
        void OnJump(InputAction.CallbackContext context);
    }
}
